on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

permissions:
  contents: read

name: Build

jobs:
  build_and_test:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=x86_64-pc-windows-gnu
